[package]
name = "thaw_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen-cli-support = "0.2.100"

clap = { version = "4.5", features = ["derive"] }
color-eyre = "0.6"
anyhow = "1.0"
xshell = "0.2"

toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
cargo-manifest = "0.19"

[[bin]]
name = "thaw"
path = "src/main.rs"
